//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </it is generated>
//------------------------------------------------------------------------------

namespace webapidemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentz
    {
        public string name { get; set; }
        public int id { get; set; }
    }
}
